### ISSUE TITLE
tvOS session issues

### ISSUE THREAD

**Issue by kseniya-hydric** [delannoyk/SoundcloudSDK#22]
Hi, I'm getting an error "Type 'Soundcloud' has no member 'session'" when using "if let session = Soundcloud.session". It does not recognise 'Session.login' method either for tvOS. I thought tvOS was supported? Am I missing something? The same code works fine when running on an iOS target. Thanks!

**Comment by delannoyk** [comment]
Hi @kseniya-hydric 
Yep, you're right some functions are not available on `tvOS` and this is due to a simple limitation: In order to perform a login, we have to use `OAuth` displaying a WebView. As you probably know, WebViews are not available on `tvOS` making the login and session related functions unavailable on tvOS.
I currently don't see any workaround for that. Sorry 😞
