### ISSUE TITLE
Any chance of the Swift 3 update?

### ISSUE THREAD

**Issue by kseniya-hydric** [delannoyk/SoundcloudSDK#24]
Hi, I cant get the Swift 3 on development branch to work, any chance you can get the master updated with the latest release? Thank you!

**Comment by delannoyk** [comment]
Hi, I'll be updating my repos tonight :)

**Comment by kseniya-hydric** [comment]
Hi, hope its going ok, do you have a rough date of the update? Sorry, don't mean to rush :)

**Comment by MchlG** [comment]
Would love this update :) !

**Comment by MchlG** [comment]
@kseniya-hydric have you had any luck getting your project to work in Xcode 8? Since I updated I am getting many errors no matter what version of swift and which pod version I am using. Any advice would be appreciated, thank you

**Comment by delannoyk** [comment]
Swift 2.3 version is available (0.9.1). Swift 3.0 is in progress.

**Comment by MchlG** [comment]
Awesome thank you ! All errors are gone. For some reason I am unable to login to Soundcloud and get any of the user's information. Nor am I able to load a playlist by its identifier. When I go to login instead of bringing me to the Soundcloud Login view, it displays a page that says "invalid_request: Required parameter is missing: client_id"

and to the console it logs : 
2016-09-20 10:15:19.116702 <APPNAME>[1873:408005] -canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "This app is not allowed to query for scheme org-appextension-feature-password-management"

Also logged to the console is: 

2016-09-20 10:08:31.666707 <APPNAME>[1866:406905] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-09-20 10:08:31.680209 <APPNAME>[1866:406905] [MC] Reading from public effective user settings.

Then after 15 seconds or so this is logged : 

2016-09-20 10:18:24.949276 <APPNAME>[1887:409216] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2016-09-20 10:18:24.954530 <APPNAME>[1887:409216] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
2016-09-20 10:18:37.277417 <APPNAME>[1887:409216] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2016-09-20 10:18:37.283465 <APPNAME>[1887:409216] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service

Not sure if this has to do with changes iOS 10 though, but if you have any advice would be great :)

**Comment by MchlG** [comment]
Ok so I added the custom URL shceme `scheme org-appextension-feature-password-management` to my targets info.plist. Now when i go to login i get the same page displaying the words "invalid_request: Required parameter is missing: client_id" , and logged to the console is:

2016-09-20 10:44:41.030676 <APPNAME>[1937:418508] -canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

again followed shortly by another log to the console: 

2016-09-20 10:45:07.647463 <APPNAME>[1937:418508] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2016-09-20 10:45:07.653392 <APPNAME>[1937:418508] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service

**Comment by delannoyk** [comment]
You're definitely right and I'm sorry about pushing this earlier without giving it a test (don't have much time right now).
Anyway, this is fixed and tested with 0.9.2.
Come back to me for any other issue you face, I'm happy to help.

> 2016-09-20 10:44:41.030676 [1937:418508] -canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

This happens because 1Password is not installed on the device you're running your project on.

**Comment by MchlG** [comment]
Excellent, 0.9.2 is working great thank you!

**Comment by kseniya-hydric** [comment]
Hi, do you have any idea on the completion of Swift 3 version? :)

**Comment by kseniya-hydric** [comment]
Any idea on when Swift 3 version will be finished? Thanks

**Comment by trevlevieux** [comment]
I know it's tough to make the time to update. But I'd really appreciate this update as well! Thanks

**Comment by hassanabidpk** [comment]
Swift 3 version lots of error. So I am waiting for update too 😄

**Comment by delannoyk** [comment]
Ok, you can now use `master`. I'll release a new version of the pod after some more testing later.

**Comment by Gargo** [comment]
Can't run the tests:

/Users/apple/Documents/xcode_projects/SoundcloudSDK/sources/SoundcloudAppTest/ViewController.swift:10:8: Module compiled with Swift 3.0 cannot be imported in Swift 2.3: /Users/apple/Library/Developer/Xcode/DerivedData/Soundcloud-fblirnluqjdsgueoijkwaqoedgpx/Build/Products/Debug-iphonesimulator/Soundcloud.framework/Modules/Soundcloud.swiftmodule/i386.swiftmodule

**Comment by LiborZ** [comment]
Any version working with Swift 3.0? I tried latest 0.9.2 but without luck and same for developer branch (version 0.8.1). Thanks for help and for releasing working Swift 3 version

Edit: When installing version 0.9.2 (in Podfile just: "pod 'Soundcloud'") it looks like getting latest version but when I looked here at repository it's different then what is cocoapods downloading (in project I have old files, without update code to new Swift syntax). I tried to reinstall Soundcloud pod but without help.

**Comment by delannoyk** [comment]
@Gargo tests are fixed.

@LiborZ I haven't released a new pod version yet. In the meantime you can just type
`pod 'Soundcloud', :git => 'https://github.com/delannoyk/SoundcloudSDK', :branch => 'master'` in your Podfile.

**Comment by sys555** [comment]
hello!
In Swift 2.2,I couldn't build my empty project with the SoundcloudSDK.
Here are the error:
SoundcloudSDK/request/PlaylistRequest.swift:27:71: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/PlaylistRequest.swift:111:80: Cannot force unwrap value of non-optional type 'NSURL'

SoundcloudSDK/request/TrackRequest.swift:26:76: Cannot force unwrap value of non-optional type 'NSURL'

SoundcloudSDK/request/TrackRequest.swift:113:90: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/TrackRequest.swift:156:90: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/TrackRequest.swift:199:92: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/TrackRequest.swift:330:99: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/TrackRequest.swift:354:79: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/extension/NSURLExtension.swift:21:51: Cannot force unwrap value of non-optional type 'String'

Soundcloud/sources/SoundcloudSDK/request/UserRequest.swift:61:87: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/UserRequest.swift:100:89: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/UserRequest.swift:139:90: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/UserRequest.swift:178:95: Cannot force unwrap value of non-optional type 'NSURL'

SoundcloudSDK/request/UserRequest.swift:217:96: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/UserRequest.swift:309:126: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/UserRequest.swift:341:90: Cannot force unwrap value of non-optional type 'NSURL'

Soundcloud/sources/SoundcloudSDK/request/UserRequest.swift:26:76: Cannot force unwrap value of non-optional type 'NSURL'

Awesome thank you !

**Comment by delannoyk** [comment]
Hi everyone,
@sys555 0.9 is the version you're looking for. Other version are swift 2.3 or swift 3.0.

Swift 3.0 version has been released along with a new example project.

**Comment by pyanfield** [comment]
Hi @MchlG , my question is not related to the project and this issue, so sorry to bother you.
I got the error when I used WKWebView, and google it to find that you got the same error log:
`Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service`
I want to know if you got the way to fix it.

**Comment by MchlG** [comment]
@pyanfield hello, I used version 0.9.2 of this repo and the issue was fixed. This was back in September though and I haven't tried it out since then so a lot may have changed! Good luck
